Fixed error Unhandled Rejection (TypeError): this.cleanCustomerNameData is not a function, so the information to be displayed on the DataDiscoveryPage and search control works properly.